spring:
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
  application:
    name: userserver
server:
  context-path: /userServer
  port: 7071
eureka:
  instance:
    appname: userServer
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
